project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
      search: false
      background: "#f8f9fa"
      left: 
      - href: index.qmd
        text: Home
      right:
      - icon: linkedin
        href: https://www.linkedin.com/in/angel-rutherford/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/aruth3
        aria-label: GitHub
      - icon: envelope
        href: mailto:aruth3@design.upenn.edu
        aria-label: Email
            

format:
  html:
    theme: lux
    toc: false
    code-fold: true

execute:
  freeze: auto
