<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Angel Rutherford">
<meta name="dcterms.date" content="2025-11-18">

<title>Assignment 4: Spatial Predictive Analysis – Angel Rutherford - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Angel Rutherford - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-notes" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Weekly Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-weekly-notes">    
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-01-notes.html">
 <span class="dropdown-text">Week 1</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Assignments</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="../../assignments/assignment_1/assignment_1.html">
 <span class="dropdown-text">Assignment 1: Census Data Quality for Policy Decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment_2/Rutherford_Angel_Assignment2.html">
 <span class="dropdown-text">Assignment 2: Spatial Analysis and Visualization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment_3(midterm)/Rutherford_Angel_Appendix.html">
 <span class="dropdown-text">Midterm: Philadelphia Housing Model - Technical Appendix</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment_3(midterm)/Rutherford_Angel_Presentation.html">
 <span class="dropdown-text">Midterm: Philadelphia Housing Price Prediction - Technical Appendix</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#part-1-data-loading-exploration" id="toc-part-1-data-loading-exploration" class="nav-link" data-scroll-target="#part-1-data-loading-exploration">Part 1: Data Loading &amp; Exploration</a></li>
  <li><a href="#part-2-fishnet-grid-creation" id="toc-part-2-fishnet-grid-creation" class="nav-link" data-scroll-target="#part-2-fishnet-grid-creation">Part 2: Fishnet Grid Creation</a></li>
  <li><a href="#part-3-spatial-features" id="toc-part-3-spatial-features" class="nav-link" data-scroll-target="#part-3-spatial-features">Part 3: Spatial Features</a></li>
  <li><a href="#part-4-count-regression-models" id="toc-part-4-count-regression-models" class="nav-link" data-scroll-target="#part-4-count-regression-models">Part 4: Count Regression Models</a></li>
  <li><a href="#part-5-spatial-cross-validation" id="toc-part-5-spatial-cross-validation" class="nav-link" data-scroll-target="#part-5-spatial-cross-validation">Part 5: Spatial Cross-Validation</a></li>
  <li><a href="#part-6-model-evaluation" id="toc-part-6-model-evaluation" class="nav-link" data-scroll-target="#part-6-model-evaluation">Part 6: Model Evaluation</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 4: Spatial Predictive Analysis</h1>
<p class="subtitle lead">Evaluating Predictive Policing Models</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Angel Rutherford </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 18, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Predictive policing is a controversial yet widely used practice that aims to prevent crime by anticipating where it is likely to occur. Police departments and vendors promote predictive policing algorithms as they ideally allow for efficient deployment of policing units, objective and data-driven analysis of crime, and an overall proactive strategy for addressing crime. Over time, predictive policing has evolved through several technical generations. One approach to predictive policing is risk terrain modeling which aims to identify the relationship between environmental features and crime. Conceptually, risk terrain modeling is aligned with the Broken Windows Theory which suggests that visible signs of neighborhood disorder lead to crime.</p>
<p>In this analysis, the risk terrain modeling framework is applied to evaluate both its predictive capacity and broader implications. Drawing on the logic of the Broken Windows Theory, the predictive model examines burglary counts in relation to the presence of vacant and abandoned buildings. According to Broken Windows Theory, areas with higher concentrations of vacant and abandoned buildings should be considered at greater risk for heightened crime.</p>
<p><br></p>
</section>
<section id="part-1-data-loading-exploration" class="level3">
<h3 class="anchored" data-anchor-id="part-1-data-loading-exploration">Part 1: Data Loading &amp; Exploration</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 1. Vacancy Dataset Dimensions Before and After Filtering and Cleaning</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Dataset</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rows</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw Vacancy Data</td>
<td style="text-align: right;">5012</td>
</tr>
<tr class="even">
<td style="text-align: left;">2017 Vacancy Data</td>
<td style="text-align: right;">422</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cleaned Vacancy Data</td>
<td style="text-align: right;">399</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><br></p>
<p>The original vacant and abandoned building dataset was filtered to only include data from 2017 and further cleaned to remove any entries with no geometry data, ensuring accuracy in our spatial analysis. The resulting dataset used for the remainder of this analysis reported 399 vacant and abandoned buildings in Chicago for 2017.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rutherford_Angel_Assignment4_files/figure-html/visualize- 311 points-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Figure 1 shows the initial exploratory visualization of vacant and abandoned buildings in Chicago : a point map showing the precise locations of individual buildings (left), and a kernel density estimation (KDE) map that highlights areas of concentrated vacancy across the city (right). Both maps illustrate the uneven distribution of vacant buildings across Chicago. The KDE map specifically reveals a dense concentration of vacant buildings in Southwest Chicago, as well as a smaller cluster of buildings in West Chicago.</p>
</section>
<section id="part-2-fishnet-grid-creation" class="level3">
<h3 class="anchored" data-anchor-id="part-2-fishnet-grid-creation">Part 2: Fishnet Grid Creation</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rutherford_Angel_Assignment4_files/figure-html/visualize-fishnet-vacant buildings-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Figure 2 depicts the distribution of vacant and abandoned houses through a fishnet grid. Fishnet grids are a staple in predictive policing because they provide evenly sized consistent spatial units that simplify analysis and reduce bias from pre-existing irregular boundaries. In this analysis, a 500 m x 500 m fishnet grid specifically is used to provide a balance between nuanced local patterns and computational ease. Compared to the kernel density map of vacant and abandoned buildings, the fishnet grid is more precise as it summarizes local cell counts, highlighting outliers in North, Northwest, and Far South Chicago and more defined clusters in West and Southwest Chicago.</p>
<p><br></p>
</section>
<section id="part-3-spatial-features" class="level3">
<h3 class="anchored" data-anchor-id="part-3-spatial-features">Part 3: Spatial Features</h3>
<p>In this analysis, two spatial features are introduced to enhance the model’s predictive power: the distance to the three nearest vacant and abandoned building and the distance to the nearest hotspot or cluster of cells with high numbers of such buildings. By combining these spatial measures with the raw counts of vacant and abandoned buildings, the model is able to capture multi-scale generalized spatial patterns as well as potential spillover effects, where the influence of vacancy extends into nearby areas.</p>
<p>The first spatial feature created in this analysis is each cell’s average distance to the three nearest vacant or abandoned buildings. This predictive model operates on the assumption that proximity to vacant or abandoned buildings is correlated with levels of crimes. Though outliers can be important, k-nearest neighbor feature as well as the distance to hotspot feature smooth the data to reveal broader spatial trends rather than a relationship to a single property. Each cell already considers the local proximity to these buildings while the k-nearest neighbor spatial feature (where k=3) introduces another spatial scale of proximity: neighborhood-level proximity.</p>
<p>The second spatial feature created for this analysis was each cell’s distance to clusters of cells with high amounts of vacant and abandoned buildings near other cells with similar high amounts, known as “High-High” clusters. These clusters theoretically symbolize hotspots or areas with significant levels of disorder. Calculating distance from these hotspots allows the model to account for regional-level spatial analysis like the one shown in the kernel density estimation map. Before calculating the distance to these hotspots, first the hotspots were identified by using a statistical measure of spatial autocorrelation, Local Moran’s I. This approach moves beyond simple counts or visual diagnostics by formally testing where clustering is statistically significant.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rutherford_Angel_Assignment4_files/figure-html/visualize-morans-vacant builduings-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>The map in Figure 3 presents the results of a Local Moran’s I spatial autocorrelation analysis. Local Moran’s I in the context of predictive policing measures how similar or dissimilar a cells value is to a set number of neighbors. In this case, the 5 nearest cells or neighbors were used to determine the level of spatial autocorrelation. While most on Chicago’s grid cells were found to be not significantly spatially correlated, there seems to be a radial effect of “High-High” clusters (red) immediately surrounded by low-value cells near high-value cells (blue) in Southeast and Southwest Chicago. The same pattern appears on a smaller scale in West Chicago as well. Each cell’s average distance was then calculated from the clusters identified as “High-High”.</p>
<p><br></p>
</section>
<section id="part-4-count-regression-models" class="level3">
<h3 class="anchored" data-anchor-id="part-4-count-regression-models">Part 4: Count Regression Models</h3>
<p>As previously mentioned, the dependent variable that the model is intended to predict is the raw counts of burglaries across Chicago. The most commonly used regression model, Ordinary Least Squares (OLS), is not appropriate in this context as OLS regression assumes continuous outcomes, constant variance in errors and the normal distribution of errors, all of which are often violated in discrete count data. In addition, OLS can generate negative predicted values, which are not theoretically meaningful for discrete, non‑negative outcomes such as crime counts.</p>
<p>In order to address these limitations, count regression models, starting with Poisson regression, were used for this analysis. Poisson regression assumes the mean and variance of observations are equal. When this assumption is violated and the variance exceeds the mean, the model exhibits overdispersion. Overdispersion can be accounted for by fitting a Negative Binomial regression model which mirrors the Poisson but differs by allowing for the mean and variance to differ. Overdispersion can be statistically measured by dividing a model’s sum of squared residuals by the model’s degrees of freedom. The threshold for problematic dispersion is when it is calculated to be greater than 1.5, indicating that a Negative Binomial model may be more appropriate. After fitting the Poisson regression model to the data and testing for overdispersion, the dispersion parameter returned a 3.6, indicating substantial overdispersion. Thus, a Negative Binomial model was also fitted. The models were then compared based on their resulting Akaike Information Criterion (AIC) which is a statistic that allows models to be compared based on their balance of complexity and predictive power. A lower AIC indicates the better model. Table 2 shows that the Negative Binomial is a more appropriate model for this anaylsis as it yields a lower AIC in addition to account for overdispersion.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 2. AIC Comparison Between Poisson and Negative Binomial Models</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Poisson</td>
<td style="text-align: right;">9843.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Negative Binomial</td>
<td style="text-align: right;">7905.93</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><br></p>
</section>
<section id="part-5-spatial-cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="part-5-spatial-cross-validation">Part 5: Spatial Cross-Validation</h3>
<p>To evaluate model’s ability generalize to unseen data, Leave-One-Group-Out Cross-Validation (LOGO-CV) was implemented, holding out entire police districts during each fold. Although the same dataset is used throughout cross-validation, the observations are split into training and test sets: the training set of districts is used to fit the model, while the excluded district serves as the test set to assess predictive performance. This specific approach of leaving one group out minimizes the impact of spatial autocorrelation and avoids spatial leakage when splitting the data into train and test groups by using entire groups of neighboring observations rather than individual cells. Furthermore, rather than using the arbitrary grid cells, using police districts as the spatial unit of measurement considers real-world deployment of police resources as it assess whether the model captures district-level crime trends. The model’s performance was assessed by calculating the prediction error metrics, Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE), per district. Table 3 reports the error metrics obtained when each district was used as the test set.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 3. LOGO CV Results by District</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Fold</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Test_District</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">N_Test</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MAE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">6.29</td>
<td style="text-align: right;">7.95</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: left;">12</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">3.70</td>
<td style="text-align: right;">4.98</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">9</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">3.70</td>
<td style="text-align: right;">4.14</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">197</td>
<td style="text-align: right;">3.64</td>
<td style="text-align: right;">4.20</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">6</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">3.32</td>
<td style="text-align: right;">4.68</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">3.29</td>
<td style="text-align: right;">3.88</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: left;">14</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">4.25</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">2.74</td>
<td style="text-align: right;">3.33</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">2.73</td>
<td style="text-align: right;">3.34</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">10</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">2.62</td>
<td style="text-align: right;">3.36</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16</td>
<td style="text-align: left;">25</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">2.59</td>
<td style="text-align: right;">3.59</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">22</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">2.82</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: left;">18</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">2.48</td>
<td style="text-align: right;">4.21</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">2.45</td>
<td style="text-align: right;">2.85</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: left;">15</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;">3.03</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">5</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;">3.21</td>
</tr>
<tr class="odd">
<td style="text-align: right;">22</td>
<td style="text-align: left;">24</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">2.36</td>
<td style="text-align: right;">3.43</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">235</td>
<td style="text-align: right;">2.32</td>
<td style="text-align: right;">3.85</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18</td>
<td style="text-align: left;">19</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">2.72</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: left;">17</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">1.87</td>
<td style="text-align: right;">2.29</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: left;">20</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">1.85</td>
</tr>
<tr class="even">
<td style="text-align: right;">19</td>
<td style="text-align: left;">16</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">1.61</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><br></p>
<p>Table 3 shows that the district the model struggles to predict the most is District 3, as it returns the highest MAE of 6.29 and a RMSE of 7.95. The table also shows the districts the model generalizes well to Districts 16, 17, and 20 as they exhibited the lowest prediction errors, with MAE values between 1.29 and 1.87 and RMSE values between 1.61 and 2.29. Most of the police districts fell into a moderate performance range, with MAE values between 2.32 and 3.70 and RMSE values between 2.72 and 4.98. Overall, the cross-validation results indicate that the model’s predictive accuracy varies substantially across police districts.</p>
<p><br></p>
</section>
<section id="part-6-model-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="part-6-model-evaluation">Part 6: Model Evaluation</h3>
<p>A baseline KDE map of burglaries was created in order to further evaluate the model’s performance. Prior to the development of risk terrain modeling, predictive policing relied on hotspot approaches which assumed that crime was most likely to occur in the same locations where it had previously occurred. This hotspot approach relies solely on past crime locations and applies spatial smoothing to identify at-risk areas. The actual locations of burglaries, the spatial model’s predictions, and the KDE baseline predictions were all plotted side-by-side in order to determine which approach more accurately captures the spatial concentration of burglaries.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rutherford_Angel_Assignment4_files/figure-html/compare-models-1.png" class="img-fluid figure-img" width="1536"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Figure 4 compares the actual count of burglaries to the model’s and KDE baseline predictions. The visual assessment of the three maps illustrates that KDE baseline prediction outperforms the complex spatial modeling in identifying concentrations of burglaries across Chicago. Table 4 further supports the conclusion drawn from the map as, because MAE and RMSE are lower for the KDE baseline than for the spatial model, the baseline achieves lower average prediction errors and exhibits fewer large errors.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 4. Model Performance Comparison</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Approach</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MAE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model</td>
<td style="text-align: right;">2.64</td>
<td style="text-align: right;">3.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">KDE</td>
<td style="text-align: right;">2.06</td>
<td style="text-align: right;">2.95</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><br></p>
<p>An additional way to assess model performance is by mapping the distribution of its errors, which reveals whether systematic spatial patterns of errors emerge within the model itself.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rutherford_Angel_Assignment4_files/figure-html/prediction-errors-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Figure 5 offers further look into the spatial distribution of the model’s errors. The map on the left of the model’s signed errors shows that the model often underestimating the amount of burglaries in high crime areas while over-predicting crimes in low crime areas. The absolute error map (right) shows that the largest prediction errors were concentrated in Districts 3, 4, and 6 in South and Southeast Chicago, followed by additional high errors in Districts 14 and 17 in the North and West. Overall, the model’s predictions were inconsistent in identifying observed burglary patterns.</p>
<p>A look into the model’s coefficients can also reflect model perform by telling us which of the model’s predictors were statistically significant and their association with risk of burglaries.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 5. Final Negative Binomial Model Coefficients (Exponentiated)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rate Ratio</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">6.818</td>
<td style="text-align: right;">0.049</td>
<td style="text-align: right;">38.795</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">countBuildings</td>
<td style="text-align: right;">1.009</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">0.359</td>
<td style="text-align: right;">0.72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">vac_buildings.nn</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-4.016</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">dist_to_hotspot</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-9.731</td>
<td style="text-align: right;">0.00</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Rate ratios &gt; 1 indicate positive association with burglary counts.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<p><br></p>
<p>Table 5 shows that the rate ratios for all predictors were close to 1, suggesting that although the spatial features were found to be statistically significant (p-value &lt; 0.05) none of the predictors substantially altered burglary risk. This indicates that the predictors contributed minimally to the model’s ability to explain or predict burglary patterns.</p>
<p><br></p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>In the scenario offered by this analysis, reliance on Broken Windows Theory and risk terrain modeling would result in ineffective deployment of police units. Both Broken Windows Theory and predictive policing approaches oversimplify crime by assuming that complex social issues can be predicted through superficial, and often stigmatized, indicators of disorder. By attempting to remain unbiased and objective, these approaches neglect the socio-historical forces that shape communities, crime, and policing, which not only undermines predictive accuracy but also increases the risk of reproducing existing inequities.</p>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>